(
 (font "klill.ttf")
 (text_colors (
               (base (0 0 0))
               (menu_selected (255 165 0))
               (alert (255 165 0))
               (p1 (128 0 0))
               (p2 (0 0 128))
               ))
 (background (texture ((name "bg_night.png") (w 11.) (h 5.))))
 (board (texture ((name "bgB.png") (w 11.) (h 5.))))
 (dice_style (animated (
                        (empty_cup ((name "emptycup.png") (y -0.07) (w 2.0) (h 2.0)))
                        (fallen_cup ((name "throwingcup.png") (y -0.07) (w 2.0) (h 2.0)))
                        (full_cup ((name "filledcup.png") (y -0.07) (w 2.) (h 2.)))
                        (dice_1 (
                                 ((name "DiceEqualone.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualone.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualone.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualzero.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualzero.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualzero.png") (x -0.25) (w 0.5) (h 0.5))
                                 ))
                        (dice_2 (
                                 ((name "DiceEqualone.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualone.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualone.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualzero.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualzero.png") (x -0.25) (w 0.5) (h 0.5))
                                 ((name "DiceEqualzero.png") (x -0.25) (w 0.5) (h 0.5))
                                 ))
                        )))
 (p1_pawn (texture ((name "Red Pawn.png"))))
 (p2_pawn (texture ((name "Blue Pawn.png"))))
 (p1_pawn_alt (texture ((name "Red Pawn(Yellow).png"))))
 (p2_pawn_alt (texture ((name "Blue Pawn(Yellow).png"))))
 (hollow_pawn (texture ((name "yellow pawn.png") (x 0.5) (y -0.5))))
 )
